/// Central SF Symbols registry — the app's icon library. Views NEVER hard-code
/// symbol names; add a case here instead so icons stay consistent.
enum Icon {
    static let skill = "shippingbox"
    static let skillFilled = "shippingbox.fill"
    static let mcp = "server.rack"
    static let sync = "arrow.triangle.2.circlepath"
    static let reload = "arrow.clockwise"
    static let add = "plus"
    static let install = "square.and.arrow.down"
    static let remove = "trash"
    static let unlink = "link.badge.plus"
    static let folder = "folder"
    static let folderFilled = "folder.fill"
    static let file = "doc.text"
    static let fileGeneric = "doc"
    static let image = "photo"
    static let code = "chevron.left.forwardslash.chevron.right"
    static let warning = "exclamationmark.triangle.fill"
    static let error = "xmark.octagon.fill"
    static let success = "checkmark.circle.fill"
    static let info = "info.circle.fill"
    static let update = "arrow.down.circle"
    static let activity = "list.bullet.rectangle"
    static let user = "person.crop.circle"
    static let project = "folder.badge.gearshape"
    static let search = "magnifyingglass"
    static let close = "xmark"
    static let copy = "doc.on.doc"
    static let reveal = "arrow.up.forward.app"
    static let symlink = "link"
    static let help = "questionmark.circle"
    static let sidebar = "sidebar.left"
    static let sparkles = "square.grid.2x2"
}
