[package]
name = "synca-cli"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
synca-core = { path = "../synca-core" }
synca-tui = { path = "../synca-tui" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
